M48
; DRILL file {KiCad (6.0.9)} date Sat Dec 17 18:28:32 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-17T18:28:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X4.7Y-3.4
X5.3Y-3.4
T2
X4.7Y-3.8
X4.8Y-3.8
T3
X5.2Y-3.8
X5.3Y-3.8
T0
M30
